site_name: EMWaver
theme:
  name: material
  features:
    - navigation.tabs
  logo: logo.png
  favicon: logo.png
  toc:
    permalink: false
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  toc:
    sidebar: false
nav:
  - Home: index.md
  - Technical Implementation: technical_implementation.md
  - Firmware Update: firmware.md
  - Buy EMWaver: https://brave-desert-0fdc19403.6.azurestaticapps.net/
extra_css:
  - styles/hide-toc.css
