#pragma once

#include "driver/gpio.h"
#include "sdkconfig.h"

#if defined(CONFIG_IDF_TARGET_ESP32S2)
#define EMW_TARGET_BOARD_TYPE "esp32s2"
#define EMW_TARGET_DEVICE_NAME_PREFIX "ESP32-S2"
#define EMW_TARGET_CAPABILITIES "wifi,usb"
#define EMW_TARGET_HAS_BLE 0
#define EMW_TARGET_IR_TX_PIN_SHIELD GPIO_NUM_NC
#elif defined(CONFIG_IDF_TARGET_ESP32S3)
#define EMW_TARGET_BOARD_TYPE "esp32s3"
#define EMW_TARGET_DEVICE_NAME_PREFIX "ESP32-S3"
#define EMW_TARGET_CAPABILITIES "wifi,usb,ble"
#define EMW_TARGET_HAS_BLE 1
#define EMW_TARGET_IR_TX_PIN_SHIELD GPIO_NUM_37
#else
#define EMW_TARGET_BOARD_TYPE CONFIG_IDF_TARGET
#define EMW_TARGET_DEVICE_NAME_PREFIX "ESP32"
#define EMW_TARGET_CAPABILITIES "wifi,usb"
#define EMW_TARGET_HAS_BLE 0
#define EMW_TARGET_IR_TX_PIN_SHIELD GPIO_NUM_NC
#endif

#if CONFIG_FREERTOS_UNICORE
#define EMW_TARGET_COMMAND_CORE PRO_CPU_NUM
#else
#define EMW_TARGET_COMMAND_CORE APP_CPU_NUM
#endif
