#pragma once

#include "driver/gpio.h"
#include "sdkconfig.h"

#if defined(CONFIG_IDF_TARGET_ESP32S2)
#define EMW_TARGET_BOARD_TYPE "esp32s2"
#define EMW_TARGET_DEVICE_NAME_PREFIX "ESP32-S2"
#define EMW_TARGET_CAPABILITIES "wifi,usb"
#define EMW_TARGET_HAS_BLE 0
#define EMW_TARGET_IR_TX_PIN_SHIELD GPIO_NUM_NC
#define EMW_TARGET_STARTUP_LED GPIO_NUM_1
#define EMW_TARGET_SPI_DEFAULT_MISO 13
#define EMW_TARGET_SPI_DEFAULT_MOSI 11
#define EMW_TARGET_SPI_DEFAULT_SCK 12
#define EMW_TARGET_SPI_DEFAULT_CS 10
#elif defined(CONFIG_IDF_TARGET_ESP32S3)
#define EMW_TARGET_BOARD_TYPE "esp32s3"
#define EMW_TARGET_DEVICE_NAME_PREFIX "ESP32-S3"
#if defined(CONFIG_BT_NIMBLE_ENABLED) && CONFIG_BT_NIMBLE_ENABLED
#define EMW_TARGET_CAPABILITIES "wifi,usb,ble"
#define EMW_TARGET_HAS_BLE 1
#else
#define EMW_TARGET_CAPABILITIES "wifi,usb"
#define EMW_TARGET_HAS_BLE 0
#endif
#define EMW_TARGET_IR_TX_PIN_SHIELD GPIO_NUM_37
#define EMW_TARGET_STARTUP_LED GPIO_NUM_1
#define EMW_TARGET_SPI_DEFAULT_MISO 13
#define EMW_TARGET_SPI_DEFAULT_MOSI 11
#define EMW_TARGET_SPI_DEFAULT_SCK 12
#define EMW_TARGET_SPI_DEFAULT_CS 10
#elif defined(CONFIG_IDF_TARGET_ESP32)
#define EMW_TARGET_BOARD_TYPE "esp32"
#define EMW_TARGET_DEVICE_NAME_PREFIX "ESP32"
#if defined(CONFIG_BT_NIMBLE_ENABLED) && CONFIG_BT_NIMBLE_ENABLED
#define EMW_TARGET_CAPABILITIES "wifi,ble"
#define EMW_TARGET_HAS_BLE 1
#else
#define EMW_TARGET_CAPABILITIES "wifi"
#define EMW_TARGET_HAS_BLE 0
#endif
#define EMW_TARGET_IR_TX_PIN_SHIELD GPIO_NUM_NC
#define EMW_TARGET_STARTUP_LED GPIO_NUM_2
#define EMW_TARGET_SPI_DEFAULT_MISO 19
#define EMW_TARGET_SPI_DEFAULT_MOSI 23
#define EMW_TARGET_SPI_DEFAULT_SCK 18
#define EMW_TARGET_SPI_DEFAULT_CS 21
#else
#define EMW_TARGET_BOARD_TYPE CONFIG_IDF_TARGET
#define EMW_TARGET_DEVICE_NAME_PREFIX "ESP32"
#define EMW_TARGET_CAPABILITIES "wifi,usb"
#define EMW_TARGET_HAS_BLE 0
#define EMW_TARGET_IR_TX_PIN_SHIELD GPIO_NUM_NC
#define EMW_TARGET_STARTUP_LED GPIO_NUM_2
#define EMW_TARGET_SPI_DEFAULT_MISO 13
#define EMW_TARGET_SPI_DEFAULT_MOSI 11
#define EMW_TARGET_SPI_DEFAULT_SCK 12
#define EMW_TARGET_SPI_DEFAULT_CS 10
#endif

#if CONFIG_FREERTOS_UNICORE
#define EMW_TARGET_COMMAND_CORE PRO_CPU_NUM
#else
#define EMW_TARGET_COMMAND_CORE APP_CPU_NUM
#endif
