site_name: EMWaver
theme:
  name: material
  features:
    - navigation.tabs
  logo: logo.png
  favicon: logo.png
  toc:
    permalink: false
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra:
  toc:
    sidebar: false
nav:
  - Home: index.html
  - News: news/index.html
  - Hardware: hardware.md
  - Wavelets: wavelets.md
  - EMWaver DSL: emwaver-dsl.md
  - App Overview: documentation.md
  - Firmware Update: firmware.md

extra_css:
  - styles/hide-toc.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
