#pragma once

#include "usbd_midi_if.h"

#define EMW_USB_SendResponsePkt_FS MIDI_SendResponsePkt_FS
#define EMW_USB_TrySendResponsePkt_FS MIDI_TrySendResponsePkt_FS
#define EMW_USB_ReadRxBuffer_FS MIDI_ReadRxBuffer_FS
#define EMW_USB_GetRxBufferBytesAvailable_FS MIDI_GetRxBufferBytesAvailable_FS
#define EMW_USB_FlushRxBuffer_FS MIDI_FlushRxBuffer_FS
#define EMW_USB_InitRxBuffer_FS MIDI_InitRxBuffer_FS
#define EMW_USB_FreeRxBuffer_FS MIDI_FreeRxBuffer_FS
#define EMW_USB_SendStatusPacket_FS MIDI_SendStatusPacket_FS
#define EMW_USB_Print_FS MIDI_Print_FS
#define EMW_USB_SetBufferType_FS MIDI_SetBufferType_FS
#define EMW_USB_GetBufferType_FS MIDI_GetBufferType_FS
